spring:



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: itda2024
    password: 111
    url: jdbc:mariadb://hi.newlecture.com:3306/itda2024db
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none #create-drop-update-validate

    properties:
      hibernate:
        format_sql: true

